### ISSUE TITLE
hi man what do i do if i want to change the background color from white transparent to pink transparent?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [kennyh7279/plank-themes#3]
hi man what do i do if i want to change the background color from white transparent to pink transparent?

**Comment by kennyh7279** [comment]
Open the dock.theme you want to edit and look for these lines

```
#The starting color (RGBA) of the fill gradient.
FillStartColor=51;;51;;51;;180
#The ending color (RGBA) of the fill gradient.
FillEndColor=64;;64;;64;;180
```

It goes horizontally so starting color is the top and ending color is the bottom of the dock. The colors use RGBA where the last number is the alpha (transparency) of the dock.
So if you wanted hot pink for example rgb(255,105,180)

```
FillStartColor=255;;105;;180;;170
FillEndColor=255;;105;;180;;170
```

This would give you a hot pink dock with a little bit of transparency.  And you can just play with the different values to how you like it.  Hope this answers your question

**Comment by Yakumo-Yukari** [comment]
> Open the dock.theme you want to edit and look for these lines
> 
> ```
> #The starting color (RGBA) of the fill gradient.
> FillStartColor=51;;51;;51;;180
> #The ending color (RGBA) of the fill gradient.
> FillEndColor=64;;64;;64;;180
> ```
> 
> It goes horizontally so starting color is the top and ending color is the bottom of the dock. The colors use RGBA where the last number is the alpha (transparency) of the dock.
> So if you wanted hot pink for example rgb(255,105,180)
> 
> ```
> FillStartColor=255;;105;;180;;170
> FillEndColor=255;;105;;180;;170
> ```
> 
> This would give you a hot pink dock with a little bit of transparency. And you can just play with the different values to how you like it. Hope this answers your question

Cool, thank you.
